---
docker_repo: https://download.docker.com/linux/
docker_edition: ce
docker_enable_edge: false
docker_enable_test: false
docker_apt_ignore_key_error: true
docker_data_root: /var/lib/docker
docker_users:
  - vagrant
docker_allow_forward: false
docker_repo_valid_ssl: true
